Repository mnaray/USG_Website, pull requests merged in 2022-09, with the labels that each got.

#27 Adding the router and documenting new components
  .github/workflows/node.js.yml
  doc/README.md
  package-lock.json
  usg-website/package-lock.json
  usg-website/package.json
  usg-website/src/App.css
  usg-website/src/css/App.css
  usg-website/src/css/index.css
  usg-website/src/index.tsx
  usg-website/src/pages/App.tsx
  usg-website/src/pages/PageNotFound.tsx
  usg-website/src/pages/Router.tsx
  usg-website/src/tests/App.test.tsx
  usg-website/src/tests/PageNotFound.test.tsx
Labels: bug, documentation

#30 Deploy router and 404 page
  .github/workflows/node.js.yml
  doc/README.md
  package-lock.json
  usg-website/package-lock.json
  usg-website/package.json
  usg-website/src/App.css
  usg-website/src/css/App.css
  usg-website/src/css/index.css
  usg-website/src/index.tsx
  usg-website/src/pages/App.tsx
  usg-website/src/pages/PageNotFound.tsx
  usg-website/src/pages/Router.tsx
  usg-website/src/tests/App.test.tsx
  usg-website/src/tests/PageNotFound.test.tsx
Labels: deployment

#31 add redirects for netlify
  usg-website/public/_redirects
Labels: deployment

#32 Expand Readme of the first page.
  README.md
  doc/README.md
  doc/assets/20220912_191512_fork.jpg
Labels: documentation, enhancement

#34 Interactive Low-Fi Mockup
  doc/mockups/Lo-Fi_USG.drawio
Labels: documentation, customer interaction needed, testing

#38 Kontributionsreglement erstellt
  README.md
  doc/README.md
Labels: documentation, enhancement

#41 Lizenzierung angepasst
  LICENSE
  README.md
  doc/README.md
Labels: documentation, deployment

#45 change test case titles
  usg-website/src/tests/App.test.tsx
Labels: testing, lint/refactor

#44 clean unused line
  usg-website/src/tests/PageNotFound.test.tsx
Labels: lint/refactor

#52 Add Slogan Component
  doc/README.md
  usg-website/src/pages/Home.tsx
  usg-website/src/pages/components/Button.tsx
  usg-website/src/pages/components/Slogan.tsx
Labels: component

#57 56 forms komponente und doku
  doc/README.md
  usg-website/src/pages/components/GoogleForms.tsx
Labels: documentation, component
